dofile("./AI/USER_AI/RNAI/Const.lua")
dofile("./AI/USER_AI/RNAI/SkillData.lua")
dofile("./AI/USER_AI/RNAI/HomCfg.lua")
dofile("./AI/USER_AI/RNAI/Geo.lua")
dofile("./AI/USER_AI/RNAI/tablelib.lua")
dofile("./AI/USER_AI/RNAI/MapInfo.lua")
dofile("./AI/USER_AI/RNAI/Main.lua")
